version: '3.3'

services:
  world-of-games:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: world_of_games_app
    ports:
      - "5001:5001"
    environment:
      - FLASK_APP=rest_app.py
      - FLASK_RUN_HOST=0.0.0.0
    volumes:
      - .:/app
    restart: unless-stopped